server:
  port: 8088


spring:
  application:
    #集群名称
    name: cloud-api-business
  datasource:
    druid:
      url: jdbc:mysql://47.107.110.112:3306/huaqi?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #注册服务中心url
      defaultZone: http://localhost:10096/eureka
    should-enforce-registration-at-init: true
  instance:
    #实例名称
    instance-id: api-business-${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12

mybatis:
  mapper-locations: classpath:**/*Mapper.xml
#基于注解mybatis不用配置