server:
  port: 5088


spring:
  application:
    name: cloud-api-calculate
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #注册服务中心url
      defaultZone: http://localhost:10096/eureka
  #服务实例名称
  instance:
    instance-id: api-calculate-${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic

logging:
  level:
    cn.edu.whu.huaqi_2020: debug