server:
  port: 7001

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12
  client:
    #该eureka服务端不用自己注册自己
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #注册服务中心url
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/