server:
  port: 9555


spring:
  application:
    name: cloud-gateway
  cloud:
    #像极了nginx反向代理，但是网关拥有保护的功能，无法直接访问路由转发的地址
    gateway:
      routes:
        #路由id唯一即可
        - id: api_calculate_route
          uri: lb://cloud-api-calculate
          predicates:
            - Path=/api/calculate/**

        - id: api_business_route
          #路由转发
          uri: lb://cloud-api-business
          predicates:
            - Path=/api/business/**

        - id: api_user_route
            #路由转发
          uri: lb://cloud-api-user
          predicates:
            - Path=/api/user/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #注册服务中心url
      defaultZone: http://localhost:10096/eureka
  #服务实例名称
  instance:
    instance-id: getway-${server.port}
    prefer-ip-address: true