eureka:
  client:
    enabled: false

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/huaqi?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      password: root